version: '3.8'

services:
  postgres:
    image: postgres:latest #hub.docker.com/_/postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
  redis:
    image: redis:latest #hub.docker.com/_/redis
    ports:
      - "6379:6379"
    